create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  image text not null,
  images jsonb default '[]'::jsonb,
  category text not null,
  price text not null,
  sale_price text,
  featured boolean default false,
  is_new boolean default false,
  description text,
  material text,
  dimensions text,
  status text default 'active',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  name_en text not null default '',
  description text not null default '',
  sort_order integer default 100,
  status text default 'active',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_name text not null,
  phone text not null,
  email text,
  address text,
  note text,
  product_slug text,
  product_name text,
  quantity integer default 1,
  items jsonb default '[]'::jsonb,
  payment_method text default 'cod',
  status text default 'pending',
  revenue_amount integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.orders add column if not exists revenue_amount integer default 0;
alter table public.orders add column if not exists updated_at timestamptz default now();
alter table public.products add column if not exists images jsonb default '[]'::jsonb;

create index if not exists products_status_category_idx on public.products (status, category);
create index if not exists products_featured_idx on public.products (featured desc, id asc);
create index if not exists categories_status_sort_idx on public.categories (status, sort_order asc);
create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status);

alter table public.products enable row level security;
alter table public.categories enable row level security;
alter table public.orders enable row level security;

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products"
on public.products for select
using (status = 'active');

drop policy if exists "Public can read active categories" on public.categories;
create policy "Public can read active categories"
on public.categories for select
using (status = 'active');

-- Inserts/updates are performed with SUPABASE_SERVICE_ROLE_KEY from server routes only.
