insert into public.categories (slug, name, name_en, description, sort_order, status) values
('ban-ghe-nhua-gia-may', 'Bàn ghế nhựa giả mây', 'Synthetic rattan furniture', 'Bàn ghế nhựa giả mây cho sân vườn, cafe, nhà hàng và resort.', 10, 'active'),
('ban-ghe-may-tu-nhien', 'Bàn ghế mây tự nhiên', 'Natural rattan furniture', 'Bàn ghế mây tự nhiên, sofa mây và ghế thư giãn.', 20, 'active'),
('ban-ghe-luc-binh', 'Bàn ghế lục bình', 'Water hyacinth furniture', 'Sản phẩm lục bình thủ công theo yêu cầu.', 30, 'active'),
('den-may-tre', 'Đèn mây tre', 'Rattan lamps', 'Đèn mây tre trang trí nội thất và không gian dịch vụ.', 40, 'active'),
('san-pham-khac', 'Sản phẩm khác', 'Other products', 'Các sản phẩm decor, sọt, giỏ, bình phong và phụ kiện.', 50, 'active')
on conflict (slug) do update set
name = excluded.name,
name_en = excluded.name_en,
description = excluded.description,
sort_order = excluded.sort_order,
status = excluded.status,
updated_at = now();

insert into public.products (id, slug, name, image, category, price, sale_price, featured, is_new, description, material, dimensions, status) values
(1, 'ban-ghe-noi-that-may-tre-sm48', 'Bàn ghế nội thất mây tre SM48', 'http://www.xuongghemay.com/upload/product/noithatmaytre-1-7961.jpg', 'ghe-may-tre', 'LH - 096 400 8356', '', true, true, null, null, null, 'inactive'),
(2, 'sofa-phong-khach-may-tre-sm225', 'Sofa phòng khách mây tre SM225', 'http://www.xuongghemay.com/upload/product/sofaphongkhachmaytre-2100.jpg', 'sofa-may', 'LH - 096 400 8356', '', true, true, null, null, null, 'inactive'),
(3, 'bo-sofa-may-tu-nhien-cao-cap-xgm0207', 'Bộ sofa mây tự nhiên cao cấp XGM0207', 'http://www.xuongghemay.com/upload/product/sofamaytunhiencaocap-7825.jpg', 'sofa-may', 'LH - 096 400 8356', '', true, true, null, null, null, 'inactive'),
(4, 'bo-ban-ghe-ban-cong-nhua-gia-may-xgn0206', 'Bộ bàn ghế ban công nhựa giả mây XGN0206', 'http://www.xuongghemay.com/upload/product/banghebancongnhuagiamay-5-8626.jpg', 'ban-ghe-nhua-gia-may', 'LH - 096 400 8356', '', true, true, null, null, null, 'inactive'),
(5, 'binh-phong-trang-tri-may-tre-dan-xbp204', 'Bình phong trang trí mây tre đan XBP204', 'http://www.xuongghemay.com/upload/product/binhphongtrangtrimaytredan-1-3634.jpg', 'binh-phong-may-tre', 'LH - 096 400 8356', '', true, true, null, null, null, 'inactive'),
(6, 'ghe-to-chim-check-in-treo-cay-ngoai-troi-xmt303', 'Ghế tổ chim check in treo cây ngoài trời XMT303', 'http://www.xuongghemay.com/upload/product/ghetochimcheckinngoaitroi-7-9883.jpg', 'ghe-to-chim-check-in', 'LH - 096 400 8356', '', true, true, null, null, null, 'inactive'),
(7, 'ghe-trai-tim-check-in-xmt302', 'Ghế trái tim check in XMT302', 'http://www.xuongghemay.com/upload/product/ghetraitimcheckin-5-314.jpg', 'ghe-to-chim-check-in', 'LH - 096 400 8356', '', true, true, null, null, null, 'inactive'),
(8, 'ghe-to-chim-decor-check-in-bai-bien-xmt031', 'Ghế tổ chim decor check in bãi biển XMT031', 'http://www.xuongghemay.com/upload/product/ghetochimdecorcheckinbaibien-8372.jpg', 'ghe-to-chim-check-in', 'LH - 096 400 8356', '', true, true, null, null, null, 'inactive'),
(9, 'ghe-to-chim-check-in-ngoai-troi-xgm030', 'Ghế tổ chim check in ngoài trời XGM030', 'http://www.xuongghemay.com/upload/product/ghetochimcheckinngoaitroi-1-3160.jpg', 'ghe-to-chim-check-in', 'LH - 096 400 8356', '', true, true, null, null, null, 'inactive'),
(10, 'sofa-may-phong-khach-nem-day-hien-dai-sm106', 'Sofa mây phòng khách nệm dày hiện đại SM106', 'http://www.xuongghemay.com/upload/product/sofamayphongkhachnemdayhiendai-2-7066.jpg', 'sofa-may', 'LH - 096 400 8356', '', true, true, null, null, null, 'inactive'),
(11, 'ban-ghe-may-tu-nhien-sm105', 'Bàn ghế mây tự nhiên SM105', 'http://www.xuongghemay.com/upload/product/banghemaytunhien-40-2409.jpg', 'ban-ghe-may-tu-nhien', 'LH - 096 400 8356', '', true, true, null, null, null, 'inactive'),
(12, 'ban-ghe-may-tron-sm104', 'Bàn ghế mây tròn SM104', 'http://www.xuongghemay.com/upload/product/banghemaytunhien-44-5420.jpg', 'san-pham-khac', 'LH - 096 400 8356', '', true, true, null, null, null, 'inactive'),
(13, 'ban-ghe-may-tu-nhien-sm103', 'Bàn ghế mây tự nhiên SM103', 'http://www.xuongghemay.com/upload/product/banghemaytunhien-39-7099.jpg', 'ban-ghe-may-tu-nhien', 'LH - 096 400 8356', '', false, true, null, null, null, 'inactive'),
(14, 'ban-ghe-may-tu-nhien-phong-cach-eco-sm102', 'Bàn ghế mây tự nhiên phong cách Eco SM102', 'http://www.xuongghemay.com/upload/product/banghemaytunhien-37-1304.jpg', 'ban-ghe-may-tu-nhien', 'LH - 096 400 8356', '', false, true, null, null, null, 'inactive'),
(15, 'ban-ghe-sofa-goc-may-tu-nhien-sm100', 'Bàn ghế sofa góc mây tự nhiên SM100', 'http://www.xuongghemay.com/upload/product/banghemaytunhien-35-3147.jpg', 'sofa-may', 'LH - 096 400 8356', '', false, true, null, null, null, 'inactive'),
(16, 'sofa-may-tu-nhien', 'Sofa mây tự nhiên', 'http://www.xuongghemay.com/upload/product/img2491w-6094.jpeg', 'sofa-may', 'LH - 096 400 8356', '', false, true, null, null, null, 'inactive'),
(17, 'giuong-ngu-doi-may-tu-nhien', 'Giường ngủ đôi mây tự nhiên', 'http://www.xuongghemay.com/upload/product/giuongdoimaytunhien-1-776.jpg', 'giuong-tu-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(18, 'sofa-goc-nhua-gia-may-cho-khong-gian-rong', 'sofa góc nhựa giả mây cho không gian rộng', 'http://www.xuongghemay.com/upload/product/sofagocnhuagiamaychokhonggianrong-3300.jpg', 'ban-ghe-nhua-gia-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(19, 'sofa-san-vuon-nhua-gia-may', 'sofa sân vườn nhựa giả mây', 'http://www.xuongghemay.com/upload/product/sofasanvuonnhuagiamay-1-1239.jpg', 'ban-ghe-nhua-gia-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(20, 'sofa-trung-may-tu-nhien', 'Sofa trứng mây tự nhiên', 'http://www.xuongghemay.com/upload/product/sofatrungmaytunhien-4-4377.jpg', 'sofa-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(21, 'luoi-may-nhua-dan-nong-hai', 'Lưới mây nhựa đan nong hai', 'http://www.xuongghemay.com/upload/product/luoimaynhuadannonghai-7081.jpg', 'tam-may-dan-tam-nhua-dan', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(22, 'luoi-may-dan-caro-luoi-may-caro', 'Lưới mây đan caro/ lưới mây caro', 'http://www.xuongghemay.com/upload/product/luoimaydanovuong-21-2024.jpg', 'tam-may-dan-tam-nhua-dan', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(23, 'tam-may-tre-op-tran', 'Tấm mây tre ốp trần', 'http://www.xuongghemay.com/upload/product/tammaytreoptran-1-8887.jpg', 'tam-may-dan-tam-nhua-dan', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(24, 'ban-ghe-may-tre-sm075', 'Bàn ghế mây tre SM075', 'http://www.xuongghemay.com/upload/product/banghemaytre-7-1254.jpg', 'ghe-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(25, 'gio-qua-dung-banh-may-tre-dan-td220', 'Giỏ quà đựng bánh mây tre đan TD220', 'http://www.xuongghemay.com/upload/product/gioquamaytredungbanh-2-1904.jpg', 'sot-dung-do-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(26, 'bo-4-size-khay-trung-bay-hoa-qua', 'Bộ 4 size khay trưng bày hoa quả', 'http://www.xuongghemay.com/upload/product/khaytrungbaytraicay-5-4210.jpg', 'sot-dung-do-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(27, 'bo-nhieu-size-sot-trung-bay-trai-cay-nhua-gia-may-kn12', 'Bộ nhiều size sọt trưng bày trái cây nhựa giả mây KN12', 'http://www.xuongghemay.com/upload/product/sottrungbaytraicaysieuthi-28-1107.jpg', 'ban-ghe-nhua-gia-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(28, 'khay-sot-trung-bay-trai-cay-nhua-gia-may-kieu-dang-moi-kn11', 'Khay sọt trưng bày trái cây nhựa giả mây kiểu dáng mới KN11', 'http://www.xuongghemay.com/upload/product/sottrungbaytraicaysieuthi-23-9957.jpg', 'ban-ghe-nhua-gia-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(29, 'sot-trung-bay-trai-cay-dang-vuong-cho-sieu-thi-kn06', 'Sọt trưng bày trái cây dáng vuông cho siêu thị KN06', 'http://www.xuongghemay.com/upload/product/sottrungbaytraicaysieuthi-9-8052.jpg', 'sot-dung-do-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(30, 'ghe-thu-gian-doc-sach-may-tu-nhien-cao-cap-xgm1905', 'GHẾ THƯ GIÃN ĐỌC SÁCH MÂY TỰ NHIÊN CAO CẤP XGM1905', 'http://www.xuongghemay.com/upload/product/ghebanhmaytunhien-22-1181.jpg', 'ban-ghe-may-tu-nhien', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(31, 'ghe-banh-thu-gian-kem-gac-chan-xgm279', 'Ghế bành thư giãn kèm gác chân XGM279', 'http://www.xuongghemay.com/upload/product/ghebanhmaytunhien-30-1079.jpg', 'san-pham-khac', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(32, 'ghe-thu-gian-doc-sach-may-tre-xgm248', 'Ghế thư giãn đọc sách mây tre XGM248', 'http://www.xuongghemay.com/upload/product/ghebanhmaytunhien-12-8644.jpg', 'ghe-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(33, 'ghe-banh-thu-gian-may-tu-nhien-xgm107', 'Ghế bành thư giãn mây tự nhiên XGM107', 'http://www.xuongghemay.com/upload/product/ghebanhmaytunhien-2-8465.jpg', 'ban-ghe-may-tu-nhien', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(34, 'sofa-may-sm078', 'Sofa mây SM078', 'http://www.xuongghemay.com/upload/product/sofamaysm078-1-5711.jpg', 'sofa-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(35, 'ghe-doc-sach-nhua-gia-may-xgn2403', 'Ghế Đọc Sách Nhựa Giả Mây XGN2403', 'http://www.xuongghemay.com/upload/product/ghebanhmaytunhien-26-1607.jpg', 'ban-ghe-nhua-gia-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(36, 'ghe-ban-an-may-tre-khung-trang-xgm107', 'Ghế bàn ăn mây tre khung trắng XGM107', 'http://www.xuongghemay.com/upload/product/ghebananmaytrekhungtrang-5-2946.jpg', 'ghe-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(37, 'ghe-may-nha-hang-xgm106', 'ghế mây nhà hàng XGM106', 'http://www.xuongghemay.com/upload/product/ghemaynhahang-6-3325.jpg', 'san-pham-khac', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(38, 'ban-ghe-an-nha-hang-cao-cap-xgn46', 'Bàn ghế ăn nhà hàng cao cấp XGN46', 'http://www.xuongghemay.com/upload/product/bangheannhahangcaocap-3-8173.jpg', 'san-pham-khac', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(39, 'sofa-goc-nhua-gia-may-sn209', 'Sofa góc nhựa giả mây SN209', 'http://www.xuongghemay.com/upload/product/sofagocngoaitroi-11-5058.jpg', 'ban-ghe-nhua-gia-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(40, 'ghe-sofa-dai-may-tre-xbl20', 'ghế sofa dài mây tre XBL20', 'http://www.xuongghemay.com/upload/product/ghesofadaimaytre-6-4356.jpg', 'sofa-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(41, 'ghe-sofa-don-may-tre-cao-cap-xgm301', 'Ghế Sofa Đơn Mây Tre Cao Cấp XGM301', 'http://www.xuongghemay.com/upload/product/ghesofadonmaytredancaocapxgm301-2-9566.jpg', 'sofa-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(42, 'sofa-nest-nhua-gia-may-mau-den-sang-trong-xgm204', 'Sofa Nest Nhựa Giả Mây Màu Đen Sang Trọng XGM204', 'http://www.xuongghemay.com/upload/product/sofanestnhuagiamay-1-4209.jpg', 'ban-ghe-nhua-gia-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(43, 'ghe-ban-an-may-tre-dan-xgm211', 'Ghế Bàn Ăn Mây Tre Đan XGM211', 'http://www.xuongghemay.com/upload/product/ghebananmaytredan-3-1156.jpg', 'ghe-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(44, 'ban-ghe-cafe-bistro-ngoai-troi', 'Bàn Ghế Cafe Bistro Ngoài Trời', 'http://www.xuongghemay.com/upload/product/banghecafengoaitroinhuagiamay-1-4598.jpg', 'san-pham-khac', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(45, 'binh-phong-may-tre-xbp22', 'Bình Phong Mây Tre XBP22', 'http://www.xuongghemay.com/upload/product/binhphongmaytre-9-4055.jpg', 'binh-phong-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(46, 'ghe-may-thu-gian-kem-gac-chan-xgm205', 'ghế mây thư giãn kèm gác chân XGM205', 'http://www.xuongghemay.com/upload/product/ghemaythugian-12-7850.jpg', 'san-pham-khac', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(47, 'bo-ban-ghe-may-tre-xgm203', 'bộ bàn ghế mây tre XGM203', 'http://www.xuongghemay.com/upload/product/banghemaytre-18-6088.jpg', 'ghe-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(48, 'ghe-xich-du-don-treo-tran-tgn018', 'ghế xích đu đơn treo trần TGN018', 'http://www.xuongghemay.com/upload/product/ghexichdudontreotran-4-3350.jpg', 'xich-du-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(49, 'set-ghe-thu-gian-ban-cong-nhua-gia-may-xgn54', 'set ghế thư giãn ban công nhựa giả mây XGN54', 'http://www.xuongghemay.com/upload/product/ghethugianbancong-1-1905.jpg', 'ban-ghe-nhua-gia-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(50, 'set-ban-ghe-may-tu-nhien-xgm200', 'Set bàn ghế mây tự nhiên XGM200', 'http://www.xuongghemay.com/upload/product/banghemaytunhien-21-4722.jpg', 'ban-ghe-may-tu-nhien', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(51, 'ghe-to-chim-may-tre-check-in-ngoai-troi-xmt026', 'Ghế tổ chim mây tre check in ngoài trời XMT026', 'http://www.xuongghemay.com/upload/product/ghetochimmaytrecheckinngoaitroi-2-3017.jpg', 'ghe-to-chim-check-in', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(52, 'khung-trai-tim-check-in-ngoai-troi-xmt024', 'Khung trái tim check in ngoài trời XMT024', 'http://www.xuongghemay.com/upload/product/khungtraitimcheckinngoaitroi-1-9481.jpg', 'ghe-to-chim-check-in', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(53, 'ghe-to-chim-may-tre-check-in-ngoai-troi-xmt023', 'ghế tổ chim mây tre check in ngoài trời XMT023', 'http://www.xuongghemay.com/upload/product/ghetochimmaytrecheckinngoaitroi-3-9352.jpg', 'ghe-to-chim-check-in', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(54, 'ghe-ngoi-sao-5-canh-may-tre-check-in-ngoai-troi', 'ghế ngôi sao 5 cánh mây tre check in ngoài trời', 'http://www.xuongghemay.com/upload/product/ghengoisao5canhmaytrecheckinngoaitroi-3379.jpg', 'ghe-to-chim-check-in', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(55, 'gio-qua-may-tre-dan-xgmtd209', 'giỏ quà mây tre đan XGM-TD209', 'http://www.xuongghemay.com/upload/product/gioquamaytredan-1-8934.jpg', 'sot-dung-do-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(56, 'gio-dung-qua-may-tre-dan-xgmtd208', 'giỏ đựng quà mây tre đan XGM-TD208', 'http://www.xuongghemay.com/upload/product/giodungquamaytredan-20-9744.jpg', 'sot-dung-do-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(57, 'hop-dung-qua-may-tre-dan-dang-vuong', 'hộp đựng quà mây tre đan dáng vuông', 'http://www.xuongghemay.com/upload/product/giodungquamaytredan-9-1360.jpg', 'ghe-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(58, 'gio-dung-banh-trung-thu-may-tre-dan', 'giỏ đựng bánh trung thu mây tre đan', 'http://www.xuongghemay.com/upload/product/giodungquamaytredan-13-8349.jpg', 'sot-dung-do-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(59, 'hop-dung-qua-may-tre-dan-dang-tron', 'hộp đựng quà mây tre đan dáng tròn', 'http://www.xuongghemay.com/upload/product/giodungquamaytredan-7-3273.jpg', 'ghe-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(60, 'gio-qua-may-tre-dan-dung-banh-loai-2-tang', 'giỏ quà mây tre đan đựng bánh loại 2 tầng', 'http://www.xuongghemay.com/upload/product/gioquamaytredungbanh-16-3858.jpg', 'sot-dung-do-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(61, 'ghe-to-chim-to-ken-chup-hinh', 'ghế tổ chim tổ kén chụp hình', 'http://www.xuongghemay.com/upload/product/ghetochimchuphinhngoaitroi-16-8291.jpg', 'ghe-to-chim-check-in', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(62, 'ghe-to-chim-chup-hinh-ngoai-troi-xmt016', 'ghế tổ chim chụp hình ngoài trời XMT016', 'http://www.xuongghemay.com/upload/product/ghetochimchuphinhngoaitroi-1-1810.jpg', 'ghe-to-chim-check-in', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(63, 'ban-ghe-sofa-ngoai-troi-nhua-gia-may-sn35', 'bàn ghế sofa ngoài trời nhựa giả mây SN35', 'http://www.xuongghemay.com/upload/product/sofasalonmaynhua-1-5464.jpg', 'ban-ghe-nhua-gia-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(64, 'bo-ban-ghe-trang-diem-may-tre-dan', 'bộ bàn ghế trang điểm mây tre đan', 'http://www.xuongghemay.com/upload/product/ghemaytre-15-3803.jpg', 'ghe-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(65, 'sofa-ngoai-troi-chu-l', 'Sofa ngoài trời chữ L', 'http://www.xuongghemay.com/upload/product/sofangoaitroichul-1-9585.jpg', 'sofa-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(66, 'sofa-phong-khach-may-tre-dan-sm076', 'sofa phòng khách mây tre đan SM076', 'http://www.xuongghemay.com/upload/product/banghephongkhachmaytredan-7-927.jpg', 'sofa-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(67, 'ban-ghe-may-tre-dan-khu-vuc-hien-nha', 'Bàn ghế mây tre đan khu vực hiên nhà', 'http://www.xuongghemay.com/upload/product/banghephongkhachmaytredan-11-4311.jpg', 'ghe-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(68, 'ban-ghe-sofa-may-tre-dan-sm074', 'bàn ghế sofa mây tre đan SM074', 'http://www.xuongghemay.com/upload/product/banghephongkhachmaytredan-9-2791.jpg', 'sofa-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(69, 'ban-ghe-may-tre-dan-sm073', 'bàn ghế mây tre đan SM073', 'http://www.xuongghemay.com/upload/product/banghephongkhachmaytredan-6-7685.jpg', 'ghe-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(70, 'set-ban-ghe-phong-khach-may-tre-dan', 'Set bàn ghế phòng khách mây tre đan', 'http://www.xuongghemay.com/upload/product/banghephongkhachmaytredan-4-1464.jpg', 'ghe-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(71, 'ban-ghe-phong-khach-may-tre-dan-sm071', 'ban ghe phong khach may tre dan SM071', 'http://www.xuongghemay.com/upload/product/banghephongkhachmaytredan-3-4870.jpg', 'san-pham-khac', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(72, 'ban-ghe-phong-khach-may-tre-dan-sm070', 'bàn ghế phòng khách mây tre đan SM070', 'http://www.xuongghemay.com/upload/product/banghephongkhachmaytredan-1-536.jpg', 'ghe-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(73, 'ban-ghe-tra-dao-luc-binh-dan', 'bàn ghế trà đạo lục bình đan', 'http://www.xuongghemay.com/upload/product/banghetradaolucbinhdan-3-2577.jpg', 'san-pham-khac', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(74, 'ghe-may-tre-tu-nhien-xgm101', 'Ghế mây tre tự nhiên XGM101', 'http://www.xuongghemay.com/upload/product/ghemaytrehandmade-5-2649.jpg', 'ghe-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(75, 'ghe-may-tre-handmade-xgm100', 'ghế mây tre handmade XGM100', 'http://www.xuongghemay.com/upload/product/ghemaytrehandmade-7-4189.jpg', 'ghe-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(76, 'ghe-ban-an-may-tu-nhien-hien-dai', 'ghế bàn ăn mây tự nhiên hiện đại', 'http://www.xuongghemay.com/upload/product/ghebananmaytunhien-3-8663.jpg', 'ban-ghe-may-tu-nhien', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(77, 'ghe-quay-bar-may-tu-nhien-xgm097', 'ghế quầy bar mây tự nhiên xgm097', 'http://www.xuongghemay.com/upload/product/ghequaybarmaytunhien-24-2115.jpg', 'ban-ghe-may-tu-nhien', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(78, 'vach-ngan-di-dong-may-tre-dan', 'Vách ngăn di động mây tre đan', 'http://www.xuongghemay.com/upload/product/binhphongmaytre-3259.jpg', 'ghe-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(79, 'ghe-may-xgm095', 'ghế mây xgm095', 'http://www.xuongghemay.com/upload/product/ghemay-8-4842.jpg', 'san-pham-khac', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(80, 'ban-ghe-an-may-tre-dan', 'bàn ghế ăn mây tre đan', 'http://www.xuongghemay.com/upload/product/bangheanmaytredan-18-2261.jpg', 'ghe-may-tre', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(81, 'ban-ghe-nhua-gia-may-phong-an-gia-dinh', 'bàn ghế nhựa giả mây phòng ăn gia đình', 'http://www.xuongghemay.com/upload/product/bangheannhuagiamay-29-672.jpg', 'ban-ghe-nhua-gia-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(82, 'bo-ban-ghe-an-nhua-gia-may-xgn47', 'bộ bàn ghế ăn nhựa giả mây XGN47', 'http://www.xuongghemay.com/upload/product/bangheannhuagiamay-31-1706.jpg', 'ban-ghe-nhua-gia-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(83, 'bo-ban-ghe-an-nhua-gia-may-xgn43', 'bộ bàn ghế ăn nhựa giả mây XGN43', 'http://www.xuongghemay.com/upload/product/bobangheannhuagiamay-2-6641.jpg', 'ban-ghe-nhua-gia-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(84, 'ghe-to-chim-may-tre', 'ghế tổ chim mây tre', 'http://www.xuongghemay.com/upload/product/ghetochimmaytre-3-7887.jpg', 'ghe-to-chim-check-in', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(85, 'ghe-tam-nang-be-boi', 'ghế tắm nắng bể bơi', 'http://www.xuongghemay.com/upload/product/ghetamnangbeboi-6-6096.jpg', 'san-pham-khac', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(86, 'ghe-check-in-vong-tron-mat-troi', 'ghế check in vòng tròn mặt trời', 'http://www.xuongghemay.com/upload/product/ghecheckinvongtronmattroi-1674.jpg', 'ghe-to-chim-check-in', '18 VNĐ', '', false, false, null, null, null, 'inactive'),
(87, 'ghe-may-to-chim-xmt10', 'ghế mây tổ chim XMT10', 'http://www.xuongghemay.com/upload/product/ghemaytochim-1-4615.jpg', 'ghe-to-chim-check-in', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(88, 'ghe-may-vong-tron-decor', 'Ghế mây vòng tròn decor', 'http://www.xuongghemay.com/upload/product/ghemayvongtrondecor-1-7975.jpg', 'san-pham-khac', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(89, 'sofa-nhua-gia-may-goc-chu-l', 'Sofa nhựa giả mây góc chữ L', 'http://www.xuongghemay.com/upload/product/sofanhuagiamay-33-6086.jpg', 'ban-ghe-nhua-gia-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive'),
(90, 'sofa-nhua-gia-may-sm35', 'Sofa nhua gia may sm35', 'http://www.xuongghemay.com/upload/product/sofanhuagiamaysm35-5203.jpg', 'sofa-may', 'LH - 096 400 8356', '', false, false, null, null, null, 'inactive')
on conflict (slug) do update set
name = excluded.name,
image = excluded.image,
category = excluded.category,
price = excluded.price,
sale_price = excluded.sale_price,
featured = excluded.featured,
is_new = excluded.is_new,
description = excluded.description,
material = excluded.material,
dimensions = excluded.dimensions,
status = excluded.status,
updated_at = now();
